### PR TITLE
Fix bugs from jdev branch merge, suppress new TensorFlow warnings, reindex epochs, improve diagnostics

### PR DESCRIPTION
**Pull request by felker**
Also test Jenkins server permissions after Alexey adds me to whitelist.

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by felker** [comment]
@ASvyatkovskiy

**Comment by ASvyatkovskiy** [comment]
Add to whitelist”

**Comment by ASvyatkovskiy** [comment]
Add to whitelist

**Pull request merged**
