### PR TITLE
Getting started doc for Traverse

### PR DESCRIPTION
**Pull request by iMurfyD**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by iMurfyD** [comment]
Instructions not tested yet. WIP pull request

**Comment by felker** [comment]
@iMurfyD is this ready to go?

**Comment by iMurfyD** [comment]
Sorry for the long wait replying - probably not. I'll look at it this week, and see if there's anything else that needs to be added.

**Comment by iMurfyD** [comment]
The conda environment won't build for the `master` branch, `tf2` seems ok though. Since `tf2` is the currently used branch, this seems ok to me. I added swapping to the `tf2` branch in the instructions

**Comment by iMurfyD** [comment]
Ok, this is good to go

**Pull request merged**
